<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="org.springframework.scheduling.quartz.QuartzSupportTests" tests="17" skipped="8" failures="0" errors="0" timestamp="2022-07-19T10:52:29" hostname="PACHIRA_DYH" time="5.187">
  <properties/>
  <testcase name="jobDetailWithRunnableInsteadOfJob()" classname="org.springframework.scheduling.quartz.QuartzSupportTests" time="0.001"/>
  <testcase name="schedulerRepositoryExposure()" classname="org.springframework.scheduling.quartz.QuartzSupportTests" time="0.363"/>
  <testcase name="schedulerWithHsqlDataSource()" classname="org.springframework.scheduling.quartz.QuartzSupportTests" time="3.397"/>
  <testcase name="schedulerWithQuartzJobBean()" classname="org.springframework.scheduling.quartz.QuartzSupportTests" time="0.0">
    <skipped/>
  </testcase>
  <testcase name="multipleSchedulersWithQuartzProperties()" classname="org.springframework.scheduling.quartz.QuartzSupportTests" time="0.362"/>
  <testcase name="multipleSchedulers()" classname="org.springframework.scheduling.quartz.QuartzSupportTests" time="0.05"/>
  <testcase name="schedulerAutoStartupFalse()" classname="org.springframework.scheduling.quartz.QuartzSupportTests" time="0.013"/>
  <testcase name="schedulerWithSpringBeanJobFactoryAndJobSchedulingData()" classname="org.springframework.scheduling.quartz.QuartzSupportTests" time="0.0">
    <skipped/>
  </testcase>
  <testcase name="schedulerFactoryBeanWithCustomJobStore()" classname="org.springframework.scheduling.quartz.QuartzSupportTests" time="0.162"/>
  <testcase name="schedulerAccessorBean()" classname="org.springframework.scheduling.quartz.QuartzSupportTests" time="0.0">
    <skipped/>
  </testcase>
  <testcase name="schedulerWithSpringBeanJobFactory()" classname="org.springframework.scheduling.quartz.QuartzSupportTests" time="0.0">
    <skipped/>
  </testcase>
  <testcase name="schedulerAutoStartsOnContextRefreshedEventByDefault()" classname="org.springframework.scheduling.quartz.QuartzSupportTests" time="0.006"/>
  <testcase name="schedulerWithTaskExecutor()" classname="org.springframework.scheduling.quartz.QuartzSupportTests" time="0.0">
    <skipped/>
  </testcase>
  <testcase name="schedulerWithSpringBeanJobFactoryAndQuartzJobBean()" classname="org.springframework.scheduling.quartz.QuartzSupportTests" time="0.001">
    <skipped/>
  </testcase>
  <testcase name="schedulerFactoryBeanWithApplicationContext()" classname="org.springframework.scheduling.quartz.QuartzSupportTests" time="0.575"/>
  <testcase name="twoAnonymousMethodInvokingJobDetailFactoryBeans()" classname="org.springframework.scheduling.quartz.QuartzSupportTests" time="0.0">
    <skipped/>
  </testcase>
  <testcase name="schedulerWithSpringBeanJobFactoryAndParamMismatchNotIgnored()" classname="org.springframework.scheduling.quartz.QuartzSupportTests" time="0.0">
    <skipped/>
  </testcase>
  <system-out><![CDATA[18:52:33.683 [scheduler_QuartzSchedulerThread] ERROR o.q.c.ErrorLogger - An error occurred while scanning for the next triggers to fire.
org.quartz.JobPersistenceException: Couldn't acquire next trigger: connection exception: closed
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.acquireNextTrigger(JobStoreSupport.java:2923) ~[quartz-2.3.2.jar:?]
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$41.execute(JobStoreSupport.java:2805) ~[quartz-2.3.2.jar:?]
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$41.execute(JobStoreSupport.java:2803) ~[quartz-2.3.2.jar:?]
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.executeInNonManagedTXLock(JobStoreSupport.java:3864) ~[quartz-2.3.2.jar:?]
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.acquireNextTriggers(JobStoreSupport.java:2802) ~[quartz-2.3.2.jar:?]
	at org.quartz.core.QuartzSchedulerThread.run(QuartzSchedulerThread.java:287) ~[quartz-2.3.2.jar:?]
Caused by: java.sql.SQLNonTransientConnectionException: connection exception: closed
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source) ~[hsqldb-2.5.2.jar:2.5.2]
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source) ~[hsqldb-2.5.2.jar:2.5.2]
	at org.hsqldb.jdbc.JDBCPreparedStatement.<init>(Unknown Source) ~[hsqldb-2.5.2.jar:2.5.2]
	at org.hsqldb.jdbc.JDBCConnection.prepareStatement(Unknown Source) ~[hsqldb-2.5.2.jar:2.5.2]
	at jdk.internal.reflect.GeneratedMethodAccessor152.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.quartz.impl.jdbcjobstore.AttributeRestoringConnectionInvocationHandler.invoke(AttributeRestoringConnectionInvocationHandler.java:73) ~[quartz-2.3.2.jar:?]
	at com.sun.proxy.$Proxy104.prepareStatement(Unknown Source) ~[?:?]
	at org.quartz.impl.jdbcjobstore.StdJDBCDelegate.updateTriggerStateFromOtherState(StdJDBCDelegate.java:1433) ~[quartz-2.3.2.jar:?]
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.acquireNextTrigger(JobStoreSupport.java:2901) ~[quartz-2.3.2.jar:?]
	... 5 more
Caused by: org.hsqldb.HsqlException: connection exception: closed
	at org.hsqldb.error.Error.error(Unknown Source) ~[hsqldb-2.5.2.jar:2.5.2]
	at org.hsqldb.error.Error.error(Unknown Source) ~[hsqldb-2.5.2.jar:2.5.2]
	at org.hsqldb.Session.execute(Unknown Source) ~[hsqldb-2.5.2.jar:2.5.2]
	at org.hsqldb.jdbc.JDBCPreparedStatement.<init>(Unknown Source) ~[hsqldb-2.5.2.jar:2.5.2]
	at org.hsqldb.jdbc.JDBCConnection.prepareStatement(Unknown Source) ~[hsqldb-2.5.2.jar:2.5.2]
	at jdk.internal.reflect.GeneratedMethodAccessor152.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.quartz.impl.jdbcjobstore.AttributeRestoringConnectionInvocationHandler.invoke(AttributeRestoringConnectionInvocationHandler.java:73) ~[quartz-2.3.2.jar:?]
	at com.sun.proxy.$Proxy104.prepareStatement(Unknown Source) ~[?:?]
	at org.quartz.impl.jdbcjobstore.StdJDBCDelegate.updateTriggerStateFromOtherState(StdJDBCDelegate.java:1433) ~[quartz-2.3.2.jar:?]
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.acquireNextTrigger(JobStoreSupport.java:2901) ~[quartz-2.3.2.jar:?]
	... 5 more
]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
